version:
  jquery: 3.2.1
  semantic_ui: 2.2.9
  font_awesome: 4.7.0
  moment: 2.18.0
  count_up: 1.8.2
  js_cookie: 2.1.3
  echarts: 3.4.0

google_analytics_id: UA-33449675-7
piwik_analytics_site_id: 1

repository: https://github.com/iROCKBUNNY/BYR-Navi

timezone: Asia/Shanghai

name: 北邮人导航 · BYR-Navi
author: iROCKBUNNY
author_url: http://irockbunny.com
organization: TEELAB
organization_url: http://teelab.net
description: A Navigation Website for BYR
keywords: 北邮人导航, BYR-Navi, BYR, BUPT, Navi, Navigation
url: http://byr123.irockbunny.com
contact: contact[at]irockbunny[dot]com

logo: /images/logo.png
logo_dark: /images/logo-dark.png
logo_white: /images/logo-white.png

gems:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor